service: rbi-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 768
  timeout: 10
  stage: prod
  region: us-east-1
  environment:
    MINDBODY_SITE_ID: ${env:MINDBODY_SITE_ID}
    MINDBODY_SITE_ID_SANDBOX: ${env:MINDBODY_SITE_ID_SANDBOX}
    MINDBODY_API_KEY: ${env:MINDBODY_API_KEY}
    MINDBODY_USERNAME: ${env:MINDBODY_USERNAME}
    MINDBODY_PASSWORD: ${env:MINDBODY_PASSWORD}
  iamRoleStatements: # IAM Role Permissions
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:179351698241:table/MBOToken"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

# Functions
functions:
  router:
    warmup: false
    name: ${self:service}-${self:provider.stage}
    handler: handler.router
    timeout: 15
    events:
      - http:
          path: 'v1/{proxy+}'
          method: any
