# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: rbi-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 10
  stage: prod
  region: us-east-1
  environment:
    MINDBODY_SITE_ID: ${env:MINDBODY_SITE_ID}
    MINDBODY_SITE_ID_SANDBOX: ${env:MINDBODY_SITE_ID_SANDBOX}
    MINDBODY_API_KEY: ${env:MINDBODY_API_KEY}
    MINDBODY_USERNAME: ${env:MINDBODY_USERNAME}
    MINDBODY_PASSWORD: ${env:MINDBODY_PASSWORD}
  iamRoleStatements: # IAM Role Permissions
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:179351698241:table/MBOToken"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  cageSchedule:
    warmup: false
    handler: handler.cageSchedule
    events:
      - http:
          path: 'api/cageSchedule'
          method: get
          resp: json
          cors: true
